-- =====================================================
-- 仓库管理模块表
-- =====================================================
USE warehouse_erp;

-- 仓库表
CREATE TABLE warehouse (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '仓库ID',
    warehouse_code VARCHAR(50) NOT NULL UNIQUE COMMENT '仓库编码',
    name VARCHAR(100) NOT NULL COMMENT '仓库名称',
    warehouse_type TINYINT COMMENT '仓库类型：1-成品仓,2-原料仓,3-次品仓,4-退货仓,5-冷链仓',
    state VARCHAR(50) COMMENT '州',
    city VARCHAR(50) COMMENT '城市',
    district VARCHAR(50) COMMENT '区县',
    address VARCHAR(255) COMMENT '详细地址',
    contact_person VARCHAR(50) COMMENT '联系人',
    contact_phone VARCHAR(20) COMMENT '联系电话',
    area DECIMAL(10,2) COMMENT '仓库面积(m²)',
    manager_id BIGINT COMMENT '仓库管理员ID',
    sort_order INT DEFAULT 0 COMMENT '排序',
    status TINYINT DEFAULT 1 COMMENT '状态：0-停用,1-启用',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除：0-否,1-是',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT COMMENT '创建人',
    updated_by BIGINT COMMENT '更新人',
    remark TEXT COMMENT '备注',
    INDEX idx_warehouse_code (warehouse_code),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='仓库表';

-- -- 库区表
-- CREATE TABLE warehouse_area (
--     id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '库区ID',
--     warehouse_id BIGINT NOT NULL COMMENT '仓库ID',
--     area_code VARCHAR(50) NOT NULL COMMENT '库区编码',
--     area_name VARCHAR(100) NOT NULL COMMENT '库区名称',
--     area_type TINYINT COMMENT '库区类型：1-常温区,2-冷藏区,3-冷冻区,4-危险品区',
--     sort_order INT DEFAULT 0 COMMENT '排序',
--     status TINYINT DEFAULT 1 COMMENT '状态：0-停用,1-启用',
--     is_deleted TINYINT DEFAULT 0 COMMENT '是否删除：0-否,1-是',
--     created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
--     updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
--     created_by BIGINT COMMENT '创建人',
--     updated_by BIGINT COMMENT '更新人',
--     remark TEXT COMMENT '备注',
--     UNIQUE KEY uk_warehouse_area (warehouse_id, area_code),
--     INDEX idx_warehouse_id (warehouse_id)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='库区表';

-- 库位表
CREATE TABLE warehouse_location (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '库位ID',
    warehouse_id BIGINT NOT NULL COMMENT '仓库ID',
    -- area_id BIGINT NOT NULL COMMENT '库区ID',
    location_code VARCHAR(50) NOT NULL COMMENT '库位编码',
    name VARCHAR(100) NOT NULL COMMENT '库位名称',
    shelf_no VARCHAR(50) COMMENT '货架号',
    layer_no VARCHAR(20) COMMENT '层号',
    position_no VARCHAR(20) COMMENT '位号',
    location_type TINYINT DEFAULT 1 COMMENT '库位类型：1-存储位,2-拣货位,3-收货位,4-发货位',
    max_weight DECIMAL(10,2) COMMENT '最大承重(kg)',
    max_volume DECIMAL(10,3) COMMENT '最大容积(m³)',
    sort_order INT DEFAULT 0 COMMENT '排序',
    status TINYINT DEFAULT 1 COMMENT '状态：0-停用,1-启用,2-已满',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除：0-否,1-是',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT COMMENT '创建人',
    updated_by BIGINT COMMENT '更新人',
    remark TEXT COMMENT '备注',
    UNIQUE KEY uk_location_code (warehouse_id, location_code),
    INDEX idx_warehouse_id (warehouse_id),
    INDEX idx_area_id (area_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='库位表';

-- 入库单主表
CREATE TABLE warehouse_inbound (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '入库单ID',
    inbound_no VARCHAR(50) NOT NULL UNIQUE COMMENT '入库单号',
    inbound_type TINYINT NOT NULL COMMENT '入库类型：1-采购入库,2-退货入库,3-调拨入库,4-盘盈入库,5-生产入库,6-其他入库',
    source_type TINYINT COMMENT '来源类型：1-采购订单,2-销售退货,3-调拨单',
    source_no VARCHAR(50) COMMENT '来源单号',
    warehouse_id BIGINT NOT NULL COMMENT '入库仓库ID',
    supplier_id BIGINT COMMENT '供应商ID',
    inbound_date DATE NOT NULL COMMENT '入库日期',
    expected_arrival_date DATE COMMENT '预计到货日期',
    arrival_date DATE COMMENT '实际到货日期',
    vehicle_no VARCHAR(50) COMMENT '车牌号',
    driver_name VARCHAR(50) COMMENT '司机姓名',
    driver_phone VARCHAR(20) COMMENT '司机电话',
    total_quantity DECIMAL(10,2) DEFAULT 0 COMMENT '总数量',
    total_amount DECIMAL(12,2) DEFAULT 0 COMMENT '总金额',
    operator_id BIGINT COMMENT '操作员ID',
    checker_id BIGINT COMMENT '验收员ID',
    check_date DATETIME COMMENT '验收时间',
    inbound_status TINYINT DEFAULT 1 COMMENT '入库状态：1-待入库,2-部分入库,3-已入库,4-已取消',
    audit_status TINYINT DEFAULT 0 COMMENT '审核状态：0-待审核,1-已审核,2-已驳回',
    auditor_id BIGINT COMMENT '审核人ID',
    audit_time DATETIME COMMENT '审核时间',
    audit_remark TEXT COMMENT '审核备注',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除：0-否,1-是',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT COMMENT '创建人',
    updated_by BIGINT COMMENT '更新人',
    remark TEXT COMMENT '备注',
    INDEX idx_inbound_no (inbound_no),
    INDEX idx_source_no (source_no),
    INDEX idx_warehouse_id (warehouse_id),
    INDEX idx_inbound_date (inbound_date),
    INDEX idx_inbound_status (inbound_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='入库单主表';

-- 入库单明细表
CREATE TABLE warehouse_inbound_detail (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '明细ID',
    inbound_id BIGINT NOT NULL COMMENT '入库单ID',
    inbound_no VARCHAR(50) NOT NULL COMMENT '入库单号',
    product_id BIGINT NOT NULL COMMENT '商品ID',
    batch_code VARCHAR(50) COMMENT '批次号',
    production_date DATE COMMENT '生产日期',
    expiry_date DATE COMMENT '过期日期',
    unit_id BIGINT NOT NULL COMMENT '单位ID',
    planned_quantity DECIMAL(10,2) NOT NULL COMMENT '计划数量',
    actual_quantity DECIMAL(10,2) DEFAULT 0 COMMENT '实际数量',
    qualified_quantity DECIMAL(10,2) DEFAULT 0 COMMENT '合格数量',
    unqualified_quantity DECIMAL(10,2) DEFAULT 0 COMMENT '不合格数量',
    unit_price DECIMAL(10,2) COMMENT '单价',
    amount DECIMAL(12,2) COMMENT '金额',
    location_id BIGINT COMMENT '库位ID',
    detail_status TINYINT DEFAULT 1 COMMENT '明细状态：1-待入库,2-已入库',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT COMMENT '创建人',
    updated_by BIGINT COMMENT '更新人',
    remark TEXT COMMENT '备注',
    INDEX idx_inbound_id (inbound_id),
    INDEX idx_inbound_no (inbound_no),
    INDEX idx_product_id (product_id),
    INDEX idx_batch_code (batch_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='入库单明细表';

-- 出库单主表
CREATE TABLE warehouse_outbound (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '出库单ID',
    outbound_no VARCHAR(50) NOT NULL UNIQUE COMMENT '出库单号',
    outbound_type TINYINT NOT NULL COMMENT '出库类型：1-销售出库,2-采购退货,3-调拨出库,4-盘亏出库,5-生产领料,6-报损出库,7-其他出库',
    source_type TINYINT COMMENT '来源类型：1-销售订单,2-采购退货,3-调拨单',
    source_no VARCHAR(50) COMMENT '来源单号',
    warehouse_id BIGINT NOT NULL COMMENT '出库仓库ID',
    customer_id BIGINT COMMENT '客户ID',
    outbound_date DATE NOT NULL COMMENT '出库日期',
    delivery_date DATE COMMENT '发货日期',
    expected_delivery_date DATE COMMENT '预计发货日期',
    total_quantity DECIMAL(10,2) DEFAULT 0 COMMENT '总数量',
    total_amount DECIMAL(12,2) DEFAULT 0 COMMENT '总金额',
    picker_id BIGINT COMMENT '拣货员ID',
    checker_id BIGINT COMMENT '复核员ID',
    check_date DATETIME COMMENT '复核时间',
    outbound_status TINYINT DEFAULT 1 COMMENT '出库状态：1-待拣货,2-拣货中,3-待复核,4-已出库,5-已取消',
    audit_status TINYINT DEFAULT 0 COMMENT '审核状态：0-待审核,1-已审核,2-已驳回',
    auditor_id BIGINT COMMENT '审核人ID',
    audit_time DATETIME COMMENT '审核时间',
    audit_remark TEXT COMMENT '审核备注',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除：0-否,1-是',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT COMMENT '创建人',
    updated_by BIGINT COMMENT '更新人',
    remark TEXT COMMENT '备注',
    INDEX idx_outbound_no (outbound_no),
    INDEX idx_source_no (source_no),
    INDEX idx_warehouse_id (warehouse_id),
    INDEX idx_outbound_date (outbound_date),
    INDEX idx_outbound_status (outbound_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='出库单主表';

-- 出库单明细表
CREATE TABLE warehouse_outbound_detail (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '明细ID',
    outbound_id BIGINT NOT NULL COMMENT '出库单ID',
    outbound_no VARCHAR(50) NOT NULL COMMENT '出库单号',
    product_id BIGINT NOT NULL COMMENT '商品ID',
    batch_code VARCHAR(50) COMMENT '批次号',
    unit_id BIGINT NOT NULL COMMENT '单位ID',
    planned_quantity DECIMAL(10,2) NOT NULL COMMENT '计划数量',
    actual_quantity DECIMAL(10,2) DEFAULT 0 COMMENT '实际数量',
    picked_quantity DECIMAL(10,2) DEFAULT 0 COMMENT '已拣货数量',
    unit_price DECIMAL(10,2) COMMENT '单价',
    amount DECIMAL(12,2) COMMENT '金额',
    location_id BIGINT COMMENT '库位ID',
    out_strategy TINYINT DEFAULT 1 COMMENT '出库策略：1-先进先出,2-后进先出,3-先到期先出',
    detail_status TINYINT DEFAULT 1 COMMENT '明细状态：1-待拣货,2-拣货中,3-已拣货,4-已出库',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT COMMENT '创建人',
    updated_by BIGINT COMMENT '更新人',
    remark TEXT COMMENT '备注',
    INDEX idx_outbound_id (outbound_id),
    INDEX idx_outbound_no (outbound_no),
    INDEX idx_product_id (product_id),
    INDEX idx_batch_code (batch_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='出库单明细表';

-- 库存表
CREATE TABLE warehouse_stock (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '库存ID',
    warehouse_id BIGINT NOT NULL COMMENT '仓库ID',
    location_id BIGINT COMMENT '库位ID',
    product_id BIGINT NOT NULL COMMENT '商品ID',
    batch_code VARCHAR(50) COMMENT '批次号',
    unit_id BIGINT NOT NULL COMMENT '单位ID',
    total_quantity DECIMAL(10,2) DEFAULT 0 COMMENT '总数量',
    available_quantity DECIMAL(10,2) DEFAULT 0 COMMENT '可用数量',
    locked_quantity DECIMAL(10,2) DEFAULT 0 COMMENT '锁定数量',
    allocated_quantity DECIMAL(10,2) DEFAULT 0 COMMENT '已分配数量',
    defective_quantity DECIMAL(10,2) DEFAULT 0 COMMENT '次品数量',
    cost_price DECIMAL(10,2) COMMENT '成本单价',
    total_cost DECIMAL(12,2) COMMENT '总成本',
    production_date DATE COMMENT '生产日期',
    expiry_date DATE COMMENT '过期日期',
    last_inbound_date DATETIME COMMENT '最后入库时间',
    last_outbound_date DATETIME COMMENT '最后出库时间',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_stock (warehouse_id, product_id, batch_code, location_id),
    INDEX idx_warehouse_id (warehouse_id),
    INDEX idx_product_id (product_id),
    INDEX idx_batch_code (batch_code),
    INDEX idx_expiry_date (expiry_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='库存表';

-- 库存流水表
CREATE TABLE warehouse_stock_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '流水ID',
    log_no VARCHAR(50) NOT NULL COMMENT '流水号',
    warehouse_id BIGINT NOT NULL COMMENT '仓库ID',
    location_id BIGINT COMMENT '库位ID',
    product_id BIGINT NOT NULL COMMENT '商品ID',
    batch_code VARCHAR(50) COMMENT '批次号',
    unit_id BIGINT NOT NULL COMMENT '单位ID',
    log_type TINYINT NOT NULL COMMENT '流水类型：1-入库,2-出库,3-调拨,4-盘点,5-锁定,6-解锁',
    quantity_change DECIMAL(10,2) NOT NULL COMMENT '数量变化（正数为增加，负数为减少）',
    before_quantity DECIMAL(10,2) COMMENT '变化前数量',
    after_quantity DECIMAL(10,2) COMMENT '变化后数量',
    business_type VARCHAR(50) COMMENT '业务类型',
    business_no VARCHAR(50) COMMENT '业务单号',
    operator_id BIGINT COMMENT '操作人ID',
    operation_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    remark TEXT COMMENT '备注',
    INDEX idx_log_no (log_no),
    INDEX idx_warehouse_id (warehouse_id),
    INDEX idx_product_id (product_id),
    INDEX idx_batch_code (batch_code),
    INDEX idx_business_no (business_no),
    INDEX idx_operation_time (operation_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='库存流水表';

-- 盘点单主表
CREATE TABLE warehouse_inventory (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '盘点单ID',
    inventory_no VARCHAR(50) NOT NULL UNIQUE COMMENT '盘点单号',
    inventory_type TINYINT NOT NULL COMMENT '盘点类型：1-定期盘点,2-循环盘点,3-动态盘点,4-抽查盘点',
    warehouse_id BIGINT NOT NULL COMMENT '仓库ID',
    inventory_date DATE NOT NULL COMMENT '盘点日期',
    plan_start_time DATETIME COMMENT '计划开始时间',
    plan_end_time DATETIME COMMENT '计划结束时间',
    actual_start_time DATETIME COMMENT '实际开始时间',
    actual_end_time DATETIME COMMENT '实际结束时间',
    total_product_count INT DEFAULT 0 COMMENT '盘点商品总数',
    profit_count INT DEFAULT 0 COMMENT '盘盈商品数',
    loss_count INT DEFAULT 0 COMMENT '盘亏商品数',
    inventory_status TINYINT DEFAULT 1 COMMENT '盘点状态：1-待盘点,2-盘点中,3-待审核,4-已完成,5-已取消',
    audit_status TINYINT DEFAULT 0 COMMENT '审核状态：0-待审核,1-已审核,2-已驳回',
    auditor_id BIGINT COMMENT '审核人ID',
    audit_time DATETIME COMMENT '审核时间',
    audit_remark TEXT COMMENT '审核备注',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除：0-否,1-是',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT COMMENT '创建人',
    updated_by BIGINT COMMENT '更新人',
    remark TEXT COMMENT '备注',
    INDEX idx_inventory_no (inventory_no),
    INDEX idx_warehouse_id (warehouse_id),
    INDEX idx_inventory_date (inventory_date),
    INDEX idx_inventory_status (inventory_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='盘点单主表';

-- 盘点单明细表
CREATE TABLE warehouse_inventory_detail (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '明细ID',
    inventory_id BIGINT NOT NULL COMMENT '盘点单ID',
    inventory_no VARCHAR(50) NOT NULL COMMENT '盘点单号',
    product_id BIGINT NOT NULL COMMENT '商品ID',
    batch_code VARCHAR(50) COMMENT '批次号',
    location_id BIGINT COMMENT '库位ID',
    unit_id BIGINT NOT NULL COMMENT '单位ID',
    book_quantity DECIMAL(10,2) DEFAULT 0 COMMENT '账面数量',
    actual_quantity DECIMAL(10,2) DEFAULT 0 COMMENT '实际数量',
    diff_quantity DECIMAL(10,2) DEFAULT 0 COMMENT '差异数量',
    diff_amount DECIMAL(12,2) COMMENT '差异金额',
    diff_type TINYINT COMMENT '差异类型：0-无差异,1-盘盈,2-盘亏',
    operator_id BIGINT COMMENT '盘点人ID',
    check_time DATETIME COMMENT '盘点时间',
    detail_status TINYINT DEFAULT 1 COMMENT '明细状态：1-待盘点,2-已盘点,3-已确认',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT COMMENT '创建人',
    updated_by BIGINT COMMENT '更新人',
    remark TEXT COMMENT '备注',
    INDEX idx_inventory_id (inventory_id),
    INDEX idx_inventory_no (inventory_no),
    INDEX idx_product_id (product_id),
    INDEX idx_batch_code (batch_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='盘点单明细表';

-- 调拨单主表
CREATE TABLE warehouse_transfer (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '调拨单ID',
    transfer_no VARCHAR(50) NOT NULL UNIQUE COMMENT '调拨单号',
    transfer_type TINYINT DEFAULT 1 COMMENT '调拨类型：1-仓库间调拨,2-库位间调拨',
    from_warehouse_id BIGINT NOT NULL COMMENT '调出仓库ID',
    to_warehouse_id BIGINT NOT NULL COMMENT '调入仓库ID',
    transfer_date DATE NOT NULL COMMENT '调拨日期',
    expected_arrival_date DATE COMMENT '预计到达日期',
    total_quantity DECIMAL(10,2) DEFAULT 0 COMMENT '总数量',
    total_amount DECIMAL(12,2) DEFAULT 0 COMMENT '总金额',
    transfer_status TINYINT DEFAULT 1 COMMENT '调拨状态：1-待调出,2-已调出,3-在途,4-已调入,5-已取消',
    audit_status TINYINT DEFAULT 0 COMMENT '审核状态：0-待审核,1-已审核,2-已驳回',
    auditor_id BIGINT COMMENT '审核人ID',
    audit_time DATETIME COMMENT '审核时间',
    audit_remark TEXT COMMENT '审核备注',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除：0-否,1-是',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT COMMENT '创建人',
    updated_by BIGINT COMMENT '更新人',
    remark TEXT COMMENT '备注',
    INDEX idx_transfer_no (transfer_no),
    INDEX idx_from_warehouse_id (from_warehouse_id),
    INDEX idx_to_warehouse_id (to_warehouse_id),
    INDEX idx_transfer_date (transfer_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='调拨单主表';

-- 调拨单明细表
CREATE TABLE warehouse_transfer_detail (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '明细ID',
    transfer_id BIGINT NOT NULL COMMENT '调拨单ID',
    transfer_no VARCHAR(50) NOT NULL COMMENT '调拨单号',
    product_id BIGINT NOT NULL COMMENT '商品ID',
    batch_code VARCHAR(50) COMMENT '批次号',
    from_location_id BIGINT COMMENT '调出库位ID',
    to_location_id BIGINT COMMENT '调入库位ID',
    unit_id BIGINT NOT NULL COMMENT '单位ID',
    transfer_quantity DECIMAL(10,2) NOT NULL COMMENT '调拨数量',
    actual_quantity DECIMAL(10,2) DEFAULT 0 COMMENT '实际数量',
    unit_price DECIMAL(10,2) COMMENT '单价',
    amount DECIMAL(12,2) COMMENT '金额',
    detail_status TINYINT DEFAULT 1 COMMENT '明细状态：1-待调出,2-已调出,3-已调入',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT COMMENT '创建人',
    updated_by BIGINT COMMENT '更新人',
    remark TEXT COMMENT '备注',
    INDEX idx_transfer_id (transfer_id),
    INDEX idx_transfer_no (transfer_no),
    INDEX idx_product_id (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='调拨单明细表';

