-- =====================================================
-- 采购系统模块表
-- =====================================================
USE warehouse_erp;

-- 供应商表
CREATE TABLE supplier (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '供应商ID',
    supplier_code VARCHAR(50) NOT NULL UNIQUE COMMENT '供应商编码',
    supplier_name VARCHAR(200) NOT NULL COMMENT '供应商名称',
    supplier_short_name VARCHAR(100) COMMENT '供应商简称',
    supplier_type TINYINT DEFAULT 1 COMMENT '供应商类型：1-生产商,2-贸易商,3-代理商',
    supplier_level VARCHAR(20) DEFAULT 'NORMAL' COMMENT '供应商等级：A,B,C,NORMAL',
    contact_person VARCHAR(50) COMMENT '联系人',
    contact_phone VARCHAR(20) COMMENT '联系电话',
    contact_email VARCHAR(100) COMMENT '联系邮箱',
    province VARCHAR(50) COMMENT '省份',
    city VARCHAR(50) COMMENT '城市',
    district VARCHAR(50) COMMENT '区县',
    address VARCHAR(255) COMMENT '详细地址',
    credit_code VARCHAR(50) COMMENT '统一社会信用代码',
    tax_no VARCHAR(50) COMMENT '税号',
    bank_name VARCHAR(100) COMMENT '开户银行',
    bank_account VARCHAR(50) COMMENT '银行账号',
    payment_term INT DEFAULT 0 COMMENT '账期天数',
    credit_limit DECIMAL(12,2) DEFAULT 0 COMMENT '信用额度',
    used_credit DECIMAL(12,2) DEFAULT 0 COMMENT '已用额度',
    available_credit DECIMAL(12,2) DEFAULT 0 COMMENT '可用额度',
    buyer_id BIGINT COMMENT '采购员ID',
    cooperation_date DATE COMMENT '合作日期',
    main_products TEXT COMMENT '主营产品',
    qualification_cert TEXT COMMENT '资质证书(JSON)',
    rating_score DECIMAL(3,2) COMMENT '评分(5分制)',
    status TINYINT DEFAULT 1 COMMENT '状态：0-停用,1-启用,2-黑名单',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除：0-否,1-是',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT COMMENT '创建人',
    updated_by BIGINT COMMENT '更新人',
    remark TEXT COMMENT '备注',
    INDEX idx_supplier_code (supplier_code),
    INDEX idx_supplier_name (supplier_name),
    INDEX idx_buyer_id (buyer_id),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='供应商表';

-- 供应商联系记录表
CREATE TABLE supplier_contact (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '记录ID',
    supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    contact_type TINYINT NOT NULL COMMENT '联系类型：1-电话,2-拜访,3-邮件,4-微信,5-其他',
    contact_date DATE NOT NULL COMMENT '联系日期',
    contact_person VARCHAR(50) COMMENT '联系人',
    contact_content TEXT COMMENT '联系内容',
    follow_result VARCHAR(255) COMMENT '跟进结果',
    next_follow_date DATE COMMENT '下次跟进日期',
    operator_id BIGINT COMMENT '跟进人ID',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT COMMENT '创建人',
    updated_by BIGINT COMMENT '更新人',
    INDEX idx_supplier_id (supplier_id),
    INDEX idx_contact_date (contact_date),
    INDEX idx_operator_id (operator_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='供应商联系记录表';

-- 供应商商品关联表
CREATE TABLE supplier_product (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'ID',
    supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    product_id BIGINT NOT NULL COMMENT '商品ID',
    supplier_product_code VARCHAR(50) COMMENT '供应商商品编码',
    supplier_product_name VARCHAR(200) COMMENT '供应商商品名称',
    purchase_price DECIMAL(10,2) COMMENT '采购价格',
    min_order_qty DECIMAL(10,2) COMMENT '最小起订量',
    lead_time INT COMMENT '供货周期(天)',
    is_main_supplier TINYINT DEFAULT 0 COMMENT '是否主供应商：0-否,1-是',
    status TINYINT DEFAULT 1 COMMENT '状态：0-停用,1-启用',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT COMMENT '创建人',
    updated_by BIGINT COMMENT '更新人',
    remark TEXT COMMENT '备注',
    UNIQUE KEY uk_supplier_product (supplier_id, product_id),
    INDEX idx_supplier_id (supplier_id),
    INDEX idx_product_id (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='供应商商品关联表';

-- 采购申请单主表
CREATE TABLE purchase_requisition (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '申请单ID',
    requisition_no VARCHAR(50) NOT NULL UNIQUE COMMENT '申请单号',
    requisition_type TINYINT DEFAULT 1 COMMENT '申请类型：1-常规采购,2-紧急采购,3-补充采购',
    warehouse_id BIGINT COMMENT '需求仓库ID',
    requisition_date DATE NOT NULL COMMENT '申请日期',
    required_date DATE COMMENT '需求日期',
    applicant_id BIGINT COMMENT '申请人ID',
    department_id BIGINT COMMENT '申请部门ID',
    total_quantity DECIMAL(10,2) DEFAULT 0 COMMENT '总数量',
    total_amount DECIMAL(12,2) DEFAULT 0 COMMENT '总金额',
    requisition_status TINYINT DEFAULT 1 COMMENT '申请状态：1-草稿,2-待审核,3-已审核,4-已驳回,5-已转采购',
    audit_status TINYINT DEFAULT 0 COMMENT '审核状态：0-待审核,1-已审核,2-已驳回',
    auditor_id BIGINT COMMENT '审核人ID',
    audit_time DATETIME COMMENT '审核时间',
    audit_remark TEXT COMMENT '审核备注',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除：0-否,1-是',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT COMMENT '创建人',
    updated_by BIGINT COMMENT '更新人',
    remark TEXT COMMENT '备注',
    INDEX idx_requisition_no (requisition_no),
    INDEX idx_applicant_id (applicant_id),
    INDEX idx_requisition_date (requisition_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='采购申请单主表';

-- 采购申请单明细表
CREATE TABLE purchase_requisition_detail (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '明细ID',
    requisition_id BIGINT NOT NULL COMMENT '申请单ID',
    requisition_no VARCHAR(50) NOT NULL COMMENT '申请单号',
    product_id BIGINT NOT NULL COMMENT '商品ID',
    unit_id BIGINT NOT NULL COMMENT '单位ID',
    required_quantity DECIMAL(10,2) NOT NULL COMMENT '需求数量',
    current_stock DECIMAL(10,2) COMMENT '当前库存',
    estimated_price DECIMAL(10,2) COMMENT '预估单价',
    estimated_amount DECIMAL(12,2) COMMENT '预估金额',
    required_date DATE COMMENT '需求日期',
    detail_status TINYINT DEFAULT 1 COMMENT '明细状态：1-待处理,2-已转采购',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT COMMENT '创建人',
    updated_by BIGINT COMMENT '更新人',
    remark TEXT COMMENT '备注',
    INDEX idx_requisition_id (requisition_id),
    INDEX idx_requisition_no (requisition_no),
    INDEX idx_product_id (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='采购申请单明细表';

-- 采购订单主表
CREATE TABLE purchase_order (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '采购订单ID',
    order_no VARCHAR(50) NOT NULL UNIQUE COMMENT '采购订单号',
    order_type TINYINT DEFAULT 1 COMMENT '订单类型：1-标准采购,2-紧急采购,3-框架协议',
    requisition_id BIGINT COMMENT '采购申请单ID',
    supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    warehouse_id BIGINT NOT NULL COMMENT '收货仓库ID',
    order_date DATE NOT NULL COMMENT '订单日期',
    expected_arrival_date DATE COMMENT '预计到货日期',
    buyer_id BIGINT COMMENT '采购员ID',
    payment_term INT COMMENT '账期天数',
    payment_method TINYINT COMMENT '付款方式：1-货到付款,2-预付款,3-月结,4-账期',
    prepay_ratio DECIMAL(5,2) COMMENT '预付款比例(%)',
    total_quantity DECIMAL(10,2) DEFAULT 0 COMMENT '总数量',
    total_amount DECIMAL(12,2) DEFAULT 0 COMMENT '订单金额',
    discount_amount DECIMAL(12,2) DEFAULT 0 COMMENT '折扣金额',
    freight_amount DECIMAL(12,2) DEFAULT 0 COMMENT '运费',
    other_amount DECIMAL(12,2) DEFAULT 0 COMMENT '其他费用',
    final_amount DECIMAL(12,2) DEFAULT 0 COMMENT '最终金额',
    paid_amount DECIMAL(12,2) DEFAULT 0 COMMENT '已付金额',
    unpaid_amount DECIMAL(12,2) DEFAULT 0 COMMENT '未付金额',
    order_status TINYINT DEFAULT 1 COMMENT '订单状态：1-待审核,2-待收货,3-部分收货,4-已收货,5-已完成,6-已取消',
    arrival_status TINYINT DEFAULT 0 COMMENT '到货状态：0-未到货,1-部分到货,2-已到货',
    payment_status TINYINT DEFAULT 0 COMMENT '付款状态：0-未付款,1-部分付款,2-已付款',
    audit_status TINYINT DEFAULT 0 COMMENT '审核状态：0-待审核,1-已审核,2-已驳回',
    auditor_id BIGINT COMMENT '审核人ID',
    audit_time DATETIME COMMENT '审核时间',
    audit_remark TEXT COMMENT '审核备注',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除：0-否,1-是',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT COMMENT '创建人',
    updated_by BIGINT COMMENT '更新人',
    remark TEXT COMMENT '备注',
    INDEX idx_order_no (order_no),
    INDEX idx_supplier_id (supplier_id),
    INDEX idx_order_date (order_date),
    INDEX idx_buyer_id (buyer_id),
    INDEX idx_order_status (order_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='采购订单主表';

-- 采购订单明细表
CREATE TABLE purchase_order_detail (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '明细ID',
    order_id BIGINT NOT NULL COMMENT '采购订单ID',
    order_no VARCHAR(50) NOT NULL COMMENT '采购订单号',
    requisition_detail_id BIGINT COMMENT '申请单明细ID',
    product_id BIGINT NOT NULL COMMENT '商品ID',
    unit_id BIGINT NOT NULL COMMENT '单位ID',
    quantity DECIMAL(10,2) NOT NULL COMMENT '采购数量',
    received_quantity DECIMAL(10,2) DEFAULT 0 COMMENT '已收货数量',
    returned_quantity DECIMAL(10,2) DEFAULT 0 COMMENT '已退货数量',
    unit_price DECIMAL(10,2) NOT NULL COMMENT '单价',
    discount_rate DECIMAL(5,2) DEFAULT 0 COMMENT '折扣率(%)',
    discount_amount DECIMAL(12,2) DEFAULT 0 COMMENT '折扣金额',
    amount DECIMAL(12,2) NOT NULL COMMENT '金额',
    tax_rate DECIMAL(5,2) DEFAULT 0 COMMENT '税率(%)',
    tax_amount DECIMAL(12,2) DEFAULT 0 COMMENT '税额',
    expected_arrival_date DATE COMMENT '预计到货日期',
    detail_status TINYINT DEFAULT 1 COMMENT '明细状态：1-待收货,2-部分收货,3-已收货,4-已完成',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT COMMENT '创建人',
    updated_by BIGINT COMMENT '更新人',
    remark TEXT COMMENT '备注',
    INDEX idx_order_id (order_id),
    INDEX idx_order_no (order_no),
    INDEX idx_product_id (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='采购订单明细表';

-- 采购退货单主表
CREATE TABLE purchase_return (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '退货单ID',
    return_no VARCHAR(50) NOT NULL UNIQUE COMMENT '退货单号',
    order_id BIGINT COMMENT '原采购订单ID',
    order_no VARCHAR(50) COMMENT '原采购订单号',
    supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    warehouse_id BIGINT NOT NULL COMMENT '退货仓库ID',
    return_date DATE NOT NULL COMMENT '退货日期',
    return_type TINYINT NOT NULL COMMENT '退货类型：1-质量问题,2-数量错误,3-品种错误,4-其他',
    total_quantity DECIMAL(10,2) DEFAULT 0 COMMENT '总数量',
    total_amount DECIMAL(12,2) DEFAULT 0 COMMENT '总金额',
    deduct_amount DECIMAL(12,2) DEFAULT 0 COMMENT '应扣款金额',
    actual_deduct DECIMAL(12,2) DEFAULT 0 COMMENT '实际扣款',
    return_status TINYINT DEFAULT 1 COMMENT '退货状态：1-待审核,2-待出库,3-已出库,4-已完成,5-已拒绝',
    deduct_status TINYINT DEFAULT 0 COMMENT '扣款状态：0-未扣款,1-部分扣款,2-已扣款',
    audit_status TINYINT DEFAULT 0 COMMENT '审核状态：0-待审核,1-已审核,2-已驳回',
    auditor_id BIGINT COMMENT '审核人ID',
    audit_time DATETIME COMMENT '审核时间',
    audit_remark TEXT COMMENT '审核备注',
    handler_id BIGINT COMMENT '处理人ID',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除：0-否,1-是',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT COMMENT '创建人',
    updated_by BIGINT COMMENT '更新人',
    remark TEXT COMMENT '备注',
    INDEX idx_return_no (return_no),
    INDEX idx_order_no (order_no),
    INDEX idx_supplier_id (supplier_id),
    INDEX idx_return_date (return_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='采购退货单主表';

-- 采购退货单明细表
CREATE TABLE purchase_return_detail (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '明细ID',
    return_id BIGINT NOT NULL COMMENT '退货单ID',
    return_no VARCHAR(50) NOT NULL COMMENT '退货单号',
    order_detail_id BIGINT COMMENT '原订单明细ID',
    product_id BIGINT NOT NULL COMMENT '商品ID',
    batch_code VARCHAR(50) COMMENT '批次号',
    unit_id BIGINT NOT NULL COMMENT '单位ID',
    return_quantity DECIMAL(10,2) NOT NULL COMMENT '退货数量',
    returned_quantity DECIMAL(10,2) DEFAULT 0 COMMENT '已退货数量',
    unit_price DECIMAL(10,2) NOT NULL COMMENT '单价',
    amount DECIMAL(12,2) NOT NULL COMMENT '金额',
    return_reason TEXT COMMENT '退货原因',
    handle_result VARCHAR(255) COMMENT '处理结果',
    detail_status TINYINT DEFAULT 1 COMMENT '明细状态：1-待出库,2-已出库',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT COMMENT '创建人',
    updated_by BIGINT COMMENT '更新人',
    remark TEXT COMMENT '备注',
    INDEX idx_return_id (return_id),
    INDEX idx_return_no (return_no),
    INDEX idx_product_id (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='采购退货单明细表';

-- 供应商评价表
CREATE TABLE supplier_evaluation (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '评价ID',
    supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    order_id BIGINT COMMENT '采购订单ID',
    order_no VARCHAR(50) COMMENT '采购订单号',
    evaluation_date DATE NOT NULL COMMENT '评价日期',
    quality_score DECIMAL(3,2) COMMENT '质量评分(5分制)',
    delivery_score DECIMAL(3,2) COMMENT '交付评分(5分制)',
    service_score DECIMAL(3,2) COMMENT '服务评分(5分制)',
    price_score DECIMAL(3,2) COMMENT '价格评分(5分制)',
    total_score DECIMAL(3,2) COMMENT '总分(5分制)',
    evaluation_level VARCHAR(20) COMMENT '评价等级：优秀,良好,合格,不合格',
    evaluation_content TEXT COMMENT '评价内容',
    evaluator_id BIGINT COMMENT '评价人ID',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT COMMENT '创建人',
    updated_by BIGINT COMMENT '更新人',
    INDEX idx_supplier_id (supplier_id),
    INDEX idx_order_id (order_id),
    INDEX idx_evaluation_date (evaluation_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='供应商评价表';

